### ISSUE TITLE
Links to issues from releases page don't work

### ISSUE THREAD

**Issue by timja** [jenkins-infra/plugin-site-api#88]
Problem with the [SAML](https://plugins.jenkins.io/saml) page

https://plugins.jenkins.io/saml/#releases

If you click one of the PR links you end up on https://plugins.jenkins.io/saml/issues/81/ which is a 404

## Screenshots 

![image](https://user-images.githubusercontent.com/21194782/84236306-58168d00-aaef-11ea-9bf3-69648242b3ea.png)

## Possible Solution 

Rewrite the URL to GitHub?

**Comment by halkeye** [comment]
hey cool I can transfer!

It should just be a config setting in https://github.com/jenkins-infra/plugin-site-api/blob/master/src/main/java/io/jenkins/plugins/models/PluginRelease.java though I havn't looked into it fully yet.

**Comment by halkeye** [comment]
good catch though

**Comment by timja** [comment]
Just updating my instance today 😂 very nice to have less clicks for release notes, a couple of them were using changelog.md though 👅

**Comment by halkeye** [comment]
https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-gfm-issues/src/main/java/com/vladsch/flexmark/ext/gfm/issues/internal/GfmIssuesOptions.java
https://github.com/vsch/flexmark-java/blob/43e42f6cfa178c8a7c7760997f8c7b177a28e4ad/flexmark-ext-gfm-issues/src/main/java/com/vladsch/flexmark/ext/gfm/issues/GfmIssuesExtension.java#L22

setting it right might be tricky since the prefix would have to be determined at runtime not compile time like everything is setup right now.

I'm going to mark it as newbie friendly though

**Comment by halkeye** [comment]
oh newbie friendly isn't an option here
